WeatherApp/urls.py
from django.urls import path
from .views import CityWeatherView, City_Delete
app_name = 'WeatherApp'
urlpatterns = [
    path('', CityWeatherView, name= 'city_weather'),
    path('remove/<city_name>/', City_Delete, name= 'city_remove'),
]

weather_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('WeatherApp.urls', namespace = 'WeatherApp')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

WeatherApp/models.py
from os import name
from django.db import models

# Create your models here.
class City(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

WeatherApp/forms.py
from os import name
from django.db import models
from django.db.models import fields
from django.forms import ModelForm, TextInput, widgets
from .models import City

class CityForm(ModelForm):
    class Meta:
        model = City
        fields = ['name']
        widgets = {'name' : TextInput(attrs={'class' : 'input', 'placeholder' : 'City Name'})}

WeatherApp/views.py
import requests
from django.shortcuts import get_object_or_404, render, redirect
from .models import City
from .forms import CityForm

# Create your views here.
def CityWeatherView(request):
    url = "http://api.openweathermap.org/data/2.5/weather?q={}&units=imperial&appid=4b33958249a667b6e73f6a755ebf7a85"
    errmsg = ''
    msgclass = ''
    msg = ''
    if request.method == 'POST':
        form = CityForm(request.POST)
        if form.is_valid():
            new_city = form.cleaned_data['name']
            city_count = City.objects.filter(name = new_city).count()
            if city_count == 0:
                r = r = requests.get(url.format(new_city)).json()
                if r['cod'] == 200:
                    form.save()
                else:
                    errmsg = "The city is not in the world."
            else:
                errmsg = "The city is already added to the database"
        
        if errmsg:
            msg = errmsg
            msgclass = 'is-danger'
        else:
            msg = "The city was successfully added to database."
            msgclass = 'is-success'

    form = CityForm()

    weather = []
    city = City.objects.all()
    for p in city:
        r = requests.get(url.format(p)).json()
        print(r)

        city_weather = {
            'city' : p,
            'temparature' : r['main']['temp'],
            'description' : r['weather'][0]['description'],
            'icon' : r['weather'][0]['icon'],
        }
    weather.append(city_weather)
    print(weather)
    context = {
        'weather' : weather, 'form' : form, 'msg' : msg, 'msgclass': msgclass,
    }
    return render(request, 'weather.html', context)

def City_Delete(request, city_name ):
    city = get_object_or_404(City, name = city_name)
    city.delete()
    return redirect('WeatherApp:city_weather')

templates/weather.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.css" />
</head>

<body>
    <section class="hero is-primary">
        <div class="hero-body">
            <div class="container">
                <h1 class="title">
                    What's the weather like?
                </h1>
            </div>
        </div>
    </section>
    <section class="section">
        <div class="container">
            <div class="columns">
                <div class="column is-offset-4 is-4">
                    <form method="POST">
                        {% csrf_token %}
                        <div class="field has-addons">
                            <div class="control is-expanded">
                               {{form.name}}
                            </div>
                            <div class="control">
                                <button class="button is-info">
                                    Add City
                                </button>
                            </div>
                        </div>
                        <div class="notification {{msgclass}}">
                            {{msg}}
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <section class="section">
        <div class="container">
            <div class="columns">
                <div class="column is-offset-4 is-4">
                    {% for a in weather %}
                    <div class="box">
                        <article class="media">
                            <div class="media-left">
                                <figure class="image is-50x50">
                                    <img src="http://openweathermap.org/img/w/{{a.icon}}.png" alt="Image">
                                </figure>
                            </div>
                            <div class="media-content">
                                <div class="content">
                                    <p>
                                        <span class="title">{{a.city}}</span>
                                        <br>
                                        <span class="subtitle">{{a.temparature}}° F</span>
                                        <br> {{a.description}}
                                    </p>
                                </div>
                            </div>
                            <div class="midea-right">
                                <a href="{%url 'WeatherApp:city_remove' city_name=a.city %}">
                                    <button class="delete"></button>
                                </a>
                            </div>
                        </article>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>
    <footer class="footer">
    </footer>
</body>

</html>